spring:
  config:
    activate:
      on-profile: development

  application:
    name: api

  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: study
    password: study
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      connection-init-sql: ALTER SESSION SET CURRENT_SCHEMA = "STUDY"

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect

  security:
    user:
      name: study
      password: study
